apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-container
        image: raghavanaveen/book-catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://raghava_task6_2p_user:yCatT4SeB4huzmOwCvkK5XyeT06EqDfC@dpg-crvp8l5ds78s738adcvg-a.oregon-postgres.render.com/raghava_task6_2p"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
